[versions]
springBoot = "3.2.0"
springCloud = "2023.0.0"
lombok = "1.18.30"
mapstruct = "1.5.5.Final"
resilience4j = "2.1.0"
testcontainers = "1.19.3"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-cloud-kubernetes-client = { module = "org.springframework.cloud:spring-cloud-starter-kubernetes-client" }
spring-cloud-gateway = { module = "org.springframework.cloud:spring-cloud-starter-gateway" }

postgresql = { module = "org.postgresql:postgresql" }
h2database = { module = "com.h2database:h2" }

micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }
resilience4j-spring = { module = "io.github.resilience4j:resilience4j-spring-boot3", version.ref = "resilience4j" }

mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

[bundles]
spring-web = ["spring-boot-starter-web", "spring-boot-starter-validation"]
spring-data = ["spring-boot-starter-data-jpa", "spring-boot-starter-data-redis"]
monitoring = ["spring-boot-starter-actuator", "micrometer-prometheus"]
